<?php

namespace Yaoi\Schema\Types;

use Yaoi\Schema\Exception;
use Yaoi\Schema\Transformer;

// TODO build automatically
class MultiType extends AbstractType
{
    private $typeConstraints = array();

    public function import($data)
    {
        throw new Exception('Implement me');
        // TODO: Implement import() method.
    }

    public function export($entity)
    {
        throw new Exception('Implement me');
        // TODO: Implement export() method.
    }

    public static function makeSchema()
    {
        throw new Exception('Implement me');
        // TODO: Change the autogenerated stub
    }

}